<?php
  $formcss     = 1;
  $inputborder = 'B08050';
  $numdir  = 'num5/';
  $numfil  = 'nummario';
  $bgimage = 'images/smwmountainbg.jpg';
  $font    = 'Tahoma,'.$font;
  $newthreadpic = '<img src="schemes/mario/status/mariothread.gif" align="absmiddle">';
  $newreplypic  = '<img src="schemes/mario/status/marioreply.gif" align="absmiddle">';
  $newpollpic   = '<img src="schemes/mario/status/newpollmario.gif" align="absmiddle">';
  $closedpic    = "Thread closed";
  $bgcolor    = '001144';
  $textcolor  = 'FFFFFF';
  $linkcolor  = 'FDD240';
  $linkcolor2 = 'F7AE2F';
  $linkcolor3 = 'DDFFEE';
  $linkcolor4 = 'DDEEFF';
  $tablebg1      = '301A0C url("schemes/mario/dirtbg2.png")';
  $tablebg2      = '442413 url("schemes/mario/dirtbg1.png")';
  $categorybg    = '014542 url("schemes/mario/treebg2.png")';
  $tableheadtext = 'FFFFFF';
  $tableheadbg   = '008438 url("schemes/mario/treebg1.png")';
  $tableborder   = 'CF985F';
  $scr1 = '550508';
  $scr2 = 'AA080C';
  $scr3 = 'FF2028';
  $scr4 = $scr2;
  $scr5 = $scr1;
  $scr6 = '000000';
  $scr7 = '220205';